---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi-nfs
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.1
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"

    csiDriver:
      # should be globally unique for a given cluster
      name: nfs.democratic-csi.main.cluster.local
      attachRequired: false
      fsGroupPolicy: File

    storageClasses:
      - name: nfs-client
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
        mountOptions:
          - nfsvers=4.2
          - noatime
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    volumeSnapshotClasses:
      - name: nfs-client
        deletionPolicy: Delete

    driver:
      config:
        driver: nfs-client
        instance_id:
        nfs:
          shareHost: 192.168.100.5
          shareBasePath: "/storage/democratic-csi"
          # shareHost:shareBasePath should be mounted at this location in the controller container
          controllerBasePath: "/var/mnt/persistent/democratic-csi-nfs"
          dirPermissionsMode: "0777"
          dirPermissionsUser: 105000
          dirPermissionsGroup: 105000

    controller:
      enabled: true
      strategy: deployment

      externalResizer:
        enabled: false

      driver:
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "mkdir -p /var/mnt/persistent/democratic-csi-nfs; mount 192.168.100.5:storage/democratic-csi /var/mnt/persistent/democratic-csi-nfs"]
          preStop:
            exec:
              command: ["/bin/sh","-c","umount /var/mnt/persistent/democratic-csi-nfs"]

    #   externalAttacher:
    #     image:
    #       registry: registry.k8s.io/sig-storage/csi-attacher
    #       tag: v4.10.0

    #   externalProvisioner:
    #     image:
    #       registry: registry.k8s.io/sig-storage/csi-provisioner
    #       tag: v5.3.0
    #     args:
    #       - --leader-election=false
    #       - --node-deployment=true
    #       - --node-deployment-immediate-binding=false
    #       - --feature-gates=Topology=true
    #       - --strict-topology=true
    #       - --enable-capacity=true
    #       - --capacity-ownerref-level=1

    #   externalSnapshotter:
    #     enabled: true
    #     image:
    #       registry: registry.k8s.io/sig-storage/csi-snapshotter
    #       tag: v8.2.1@sha256:5f4bb469fec51147ce157329dab598c758da1b018bad6dad26f0ff469326d769
    #     extraArgs:
    #       - --leader-election=false
    #       - --node-deployment=true

    #   tolerations:
    #     - effect: NoSchedule
    #       key: node-role.kubernetes.io/control-plane
    #       operator: Exists
    #   affinity:
    #     nodeAffinity:
    #       requiredDuringSchedulingIgnoredDuringExecution:
    #         nodeSelectorTerms:
    #           - matchExpressions:
    #               - key: "node-role.kubernetes.io/control-plane"
    #                 operator: "Exists"

    # node:
    #   driver:
    #     image:
    #       registry: ghcr.io/democratic-csi/democratic-csi
    #       tag: v1.9.3

    #   driverRegistrar:
    #     image:
    #       registry: registry.k8s.io/sig-storage/csi-node-driver-registrar
    #       tag: v2.15.0

    #   tolerations:
    #     - effect: NoSchedule
    #       key: node-role.kubernetes.io/control-plane
    #       operator: Exists





