---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./webhooks/ks.yaml
  - ./discord-notification/ks.yaml
  - ./imageupdateautomation.yaml
  - ./imagepolicies.yaml
